<Project Sdk="Godot.NET.Sdk/4.6.1">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <PublishAOT Condition="'$(RuntimeIdentifier)' != 'android-arm64'">true</PublishAOT>
    </PropertyGroup>
    <ItemGroup>
        <TrimmerRootAssembly Include="GodotSharp" />
        <TrimmerRootAssembly Include="$(TargetName)" />
    </ItemGroup>
</Project>